name: set_state_gemini
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/google_generative_ai
  google_generative_ai: ^0.2.2
  # https://pub.dev/packages/flutter_markdown
  flutter_markdown: ^0.6.20+1
  # https://pub.dev/packages/wechat_assets_picker
  wechat_assets_picker: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
